# backup/docker-compose.yaml
version: '3.8'

services:
  backup:
    image: amazon/aws-cli
    volumes:
      - ./backup-script.sh:/backup-script.sh
      - backup_data:/backup
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=auto
      - R2_ENDPOINT=${R2_ENDPOINT}
      - BUCKET_NAME=${BUCKET_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-strongpassword123}
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - MONGO_HOST=${MONGO_HOST:-mongodb}
      - MONGO_USER=${MONGO_USER:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-strongpassword123}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-strongpassword123}
    entrypoint: [ "sh", "-c", "chmod +x /backup-script.sh && while true; do /backup-script.sh; sleep 3600; done" ]
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: backend
    external: true

volumes:
  backup_data:
